// Frö-koordinater (ungefärlig mittpunkt) för länder, spridda över hela
// jorden. Spelet slumpar ett land, gör en liten slumpmässig förskjutning
// (jitter) runt mittpunkten och letar upp närmaste Street View-panorama
// därifrån (se index.html) — så bilden hamnar var som helst i landet,
// inte bara i huvudstaden. Det faktiska "rätta landet" bestäms sedan med
// omvänd geokodning av panoramats verkliga koordinat, så gränsfall (bilden
// hamnar strax över gränsen i ett grannland) blir alltid rättvist bedömda.
//
// "continent" används för delpoäng (rätt världsdel) och för kontinent-
// ledtråden i spelet.
window.STREETVIEW_COUNTRIES = [
  { name: "Sverige", lat: 62.0, lng: 15.0, continent: "Europa" },
  { name: "Norge", lat: 62.0, lng: 10.0, continent: "Europa" },
  { name: "Danmark", lat: 56.0, lng: 10.0, continent: "Europa" },
  { name: "Finland", lat: 64.0, lng: 26.0, continent: "Europa" },
  { name: "Island", lat: 65.0, lng: -18.0, continent: "Europa" },
  { name: "Storbritannien", lat: 54.0, lng: -2.0, continent: "Europa" },
  { name: "Irland", lat: 53.0, lng: -8.0, continent: "Europa" },
  { name: "Frankrike", lat: 46.6, lng: 2.4, continent: "Europa" },
  { name: "Tyskland", lat: 51.2, lng: 10.4, continent: "Europa" },
  { name: "Nederländerna", lat: 52.2, lng: 5.3, continent: "Europa" },
  { name: "Belgien", lat: 50.6, lng: 4.5, continent: "Europa" },
  { name: "Luxemburg", lat: 49.8, lng: 6.1, continent: "Europa" },
  { name: "Schweiz", lat: 46.8, lng: 8.2, continent: "Europa" },
  { name: "Österrike", lat: 47.6, lng: 14.1, continent: "Europa" },
  { name: "Italien", lat: 42.8, lng: 12.6, continent: "Europa" },
  { name: "Spanien", lat: 40.0, lng: -4.0, continent: "Europa" },
  { name: "Portugal", lat: 39.6, lng: -8.0, continent: "Europa" },
  { name: "Polen", lat: 52.0, lng: 19.0, continent: "Europa" },
  { name: "Tjeckien", lat: 49.8, lng: 15.5, continent: "Europa" },
  { name: "Slovakien", lat: 48.7, lng: 19.5, continent: "Europa" },
  { name: "Ungern", lat: 47.2, lng: 19.5, continent: "Europa" },
  { name: "Rumänien", lat: 45.9, lng: 25.0, continent: "Europa" },
  { name: "Bulgarien", lat: 42.7, lng: 25.5, continent: "Europa" },
  { name: "Grekland", lat: 39.0, lng: 22.0, continent: "Europa" },
  { name: "Kroatien", lat: 45.1, lng: 15.2, continent: "Europa" },
  { name: "Slovenien", lat: 46.1, lng: 14.8, continent: "Europa" },
  { name: "Bosnien och Hercegovina", lat: 44.2, lng: 17.8, continent: "Europa" },
  { name: "Serbien", lat: 44.0, lng: 21.0, continent: "Europa" },
  { name: "Montenegro", lat: 42.7, lng: 19.3, continent: "Europa" },
  { name: "Nordmakedonien", lat: 41.6, lng: 21.7, continent: "Europa" },
  { name: "Albanien", lat: 41.0, lng: 20.0, continent: "Europa" },
  { name: "Estland", lat: 58.6, lng: 25.0, continent: "Europa" },
  { name: "Lettland", lat: 56.9, lng: 24.6, continent: "Europa" },
  { name: "Litauen", lat: 55.3, lng: 23.9, continent: "Europa" },
  { name: "Ukraina", lat: 48.4, lng: 31.2, continent: "Europa" },
  { name: "Moldavien", lat: 47.2, lng: 28.5, continent: "Europa" },
  { name: "Malta", lat: 35.9, lng: 14.5, continent: "Europa" },
  { name: "Cypern", lat: 35.1, lng: 33.4, continent: "Europa" },

  { name: "USA", lat: 39.8, lng: -98.5, continent: "Nordamerika" },
  { name: "Kanada", lat: 56.1, lng: -106.3, continent: "Nordamerika" },
  { name: "Mexiko", lat: 23.6, lng: -102.5, continent: "Nordamerika" },
  { name: "Guatemala", lat: 15.8, lng: -90.2, continent: "Nordamerika" },
  { name: "Belize", lat: 17.2, lng: -88.5, continent: "Nordamerika" },
  { name: "Honduras", lat: 15.2, lng: -86.2, continent: "Nordamerika" },
  { name: "Costa Rica", lat: 9.7, lng: -83.8, continent: "Nordamerika" },
  { name: "Panama", lat: 8.5, lng: -80.8, continent: "Nordamerika" },
  { name: "Kuba", lat: 21.5, lng: -77.8, continent: "Nordamerika" },
  { name: "Jamaica", lat: 18.1, lng: -77.3, continent: "Nordamerika" },
  { name: "Dominikanska republiken", lat: 18.7, lng: -70.2, continent: "Nordamerika" },
  { name: "Puerto Rico", lat: 18.2, lng: -66.6, continent: "Nordamerika" },
  { name: "Colombia", lat: 4.6, lng: -74.3, continent: "Sydamerika" },
  { name: "Venezuela", lat: 6.4, lng: -66.6, continent: "Sydamerika" },
  { name: "Ecuador", lat: -1.8, lng: -78.2, continent: "Sydamerika" },
  { name: "Peru", lat: -9.2, lng: -75.0, continent: "Sydamerika" },
  { name: "Bolivia", lat: -16.3, lng: -63.6, continent: "Sydamerika" },
  { name: "Chile", lat: -35.7, lng: -71.5, continent: "Sydamerika" },
  { name: "Argentina", lat: -38.4, lng: -63.6, continent: "Sydamerika" },
  { name: "Uruguay", lat: -32.5, lng: -55.8, continent: "Sydamerika" },
  { name: "Paraguay", lat: -23.4, lng: -58.4, continent: "Sydamerika" },
  { name: "Brasilien", lat: -14.2, lng: -51.9, continent: "Sydamerika" },

  { name: "Sydafrika", lat: -30.6, lng: 22.9, continent: "Afrika" },
  { name: "Botswana", lat: -22.3, lng: 24.7, continent: "Afrika" },
  { name: "Namibia", lat: -22.9, lng: 18.5, continent: "Afrika" },
  { name: "Lesotho", lat: -29.6, lng: 28.2, continent: "Afrika" },
  { name: "Eswatini", lat: -26.5, lng: 31.5, continent: "Afrika" },
  { name: "Kenya", lat: 0.0, lng: 37.9, continent: "Afrika" },
  { name: "Uganda", lat: 1.4, lng: 32.3, continent: "Afrika" },
  { name: "Rwanda", lat: -1.9, lng: 29.9, continent: "Afrika" },
  { name: "Tanzania", lat: -6.4, lng: 34.9, continent: "Afrika" },
  { name: "Senegal", lat: 14.5, lng: -14.5, continent: "Afrika" },
  { name: "Ghana", lat: 7.9, lng: -1.0, continent: "Afrika" },
  { name: "Nigeria", lat: 9.1, lng: 8.7, continent: "Afrika" },
  { name: "Egypten", lat: 26.8, lng: 30.8, continent: "Afrika" },
  { name: "Tunisien", lat: 34.0, lng: 9.5, continent: "Afrika" },
  { name: "Marocko", lat: 31.8, lng: -7.1, continent: "Afrika" },
  { name: "Madagaskar", lat: -18.8, lng: 47.0, continent: "Afrika" },
  { name: "Mauritius", lat: -20.3, lng: 57.6, continent: "Afrika" },
  { name: "Réunion", lat: -21.1, lng: 55.5, continent: "Afrika" },

  { name: "Turkiet", lat: 39.0, lng: 35.0, continent: "Asien" },
  { name: "Israel", lat: 31.5, lng: 34.8, continent: "Asien" },
  { name: "Jordanien", lat: 31.2, lng: 36.2, continent: "Asien" },
  { name: "Förenade Arabemiraten", lat: 24.0, lng: 54.0, continent: "Asien" },
  { name: "Saudiarabien", lat: 24.0, lng: 45.0, continent: "Asien" },
  { name: "Qatar", lat: 25.3, lng: 51.2, continent: "Asien" },
  { name: "Kuwait", lat: 29.3, lng: 47.5, continent: "Asien" },
  { name: "Oman", lat: 21.5, lng: 57.5, continent: "Asien" },
  { name: "Indien", lat: 21.0, lng: 78.0, continent: "Asien" },
  { name: "Sri Lanka", lat: 7.9, lng: 80.8, continent: "Asien" },
  { name: "Nepal", lat: 28.2, lng: 84.0, continent: "Asien" },
  { name: "Bangladesh", lat: 23.7, lng: 90.4, continent: "Asien" },
  { name: "Thailand", lat: 15.9, lng: 100.9, continent: "Asien" },
  { name: "Malaysia", lat: 4.2, lng: 101.9, continent: "Asien" },
  { name: "Singapore", lat: 1.35, lng: 103.8, continent: "Asien" },
  { name: "Indonesien", lat: -2.5, lng: 118.0, continent: "Asien" },
  { name: "Filippinerna", lat: 12.9, lng: 121.8, continent: "Asien" },
  { name: "Vietnam", lat: 14.1, lng: 108.3, continent: "Asien" },
  { name: "Kambodja", lat: 12.6, lng: 105.0, continent: "Asien" },
  { name: "Laos", lat: 19.9, lng: 102.6, continent: "Asien" },
  { name: "Kina", lat: 35.0, lng: 105.0, continent: "Asien" },
  { name: "Japan", lat: 36.2, lng: 138.3, continent: "Asien" },
  { name: "Sydkorea", lat: 36.5, lng: 127.9, continent: "Asien" },
  { name: "Taiwan", lat: 23.7, lng: 121.0, continent: "Asien" },
  { name: "Mongoliet", lat: 46.9, lng: 103.8, continent: "Asien" },
  { name: "Kazakstan", lat: 48.0, lng: 66.9, continent: "Asien" },
  { name: "Georgien", lat: 42.3, lng: 43.4, continent: "Asien" },
  { name: "Armenien", lat: 40.1, lng: 45.0, continent: "Asien" },
  { name: "Azerbajdzjan", lat: 40.1, lng: 47.6, continent: "Asien" },

  { name: "Australien", lat: -25.3, lng: 133.8, continent: "Oceanien" },
  { name: "Nya Zeeland", lat: -41.0, lng: 174.0, continent: "Oceanien" }
];

// Grannländer (för "grannländer"-ledtråden). Ofullständigt utanför
// huvudlistan ovan — tomma listan [] betyder "inga landgränser (ö-nation)",
// medan att landet helt saknas här betyder att ledtråden inte har data.
window.STREETVIEW_BORDERS = {
  "Sverige": ["Norge", "Finland"],
  "Norge": ["Sverige", "Finland", "Ryssland"],
  "Danmark": ["Tyskland"],
  "Finland": ["Sverige", "Norge", "Ryssland"],
  "Island": [],
  "Storbritannien": ["Irland"],
  "Irland": ["Storbritannien"],
  "Frankrike": ["Belgien", "Luxemburg", "Tyskland", "Schweiz", "Italien", "Spanien", "Andorra", "Monaco"],
  "Tyskland": ["Danmark", "Polen", "Tjeckien", "Österrike", "Schweiz", "Frankrike", "Luxemburg", "Belgien", "Nederländerna"],
  "Nederländerna": ["Tyskland", "Belgien"],
  "Belgien": ["Frankrike", "Nederländerna", "Tyskland", "Luxemburg"],
  "Luxemburg": ["Belgien", "Tyskland", "Frankrike"],
  "Schweiz": ["Frankrike", "Tyskland", "Österrike", "Italien", "Liechtenstein"],
  "Österrike": ["Tyskland", "Tjeckien", "Slovakien", "Ungern", "Slovenien", "Italien", "Schweiz", "Liechtenstein"],
  "Italien": ["Frankrike", "Schweiz", "Österrike", "Slovenien", "San Marino", "Vatikanstaten"],
  "Spanien": ["Frankrike", "Portugal", "Andorra"],
  "Portugal": ["Spanien"],
  "Polen": ["Tyskland", "Tjeckien", "Slovakien", "Ukraina", "Vitryssland", "Litauen"],
  "Tjeckien": ["Tyskland", "Polen", "Slovakien", "Österrike"],
  "Slovakien": ["Tjeckien", "Polen", "Ungern", "Ukraina", "Österrike"],
  "Ungern": ["Österrike", "Slovakien", "Ukraina", "Rumänien", "Serbien", "Kroatien", "Slovenien"],
  "Rumänien": ["Ungern", "Ukraina", "Moldavien", "Bulgarien", "Serbien"],
  "Bulgarien": ["Rumänien", "Serbien", "Nordmakedonien", "Grekland", "Turkiet"],
  "Grekland": ["Albanien", "Nordmakedonien", "Bulgarien", "Turkiet"],
  "Kroatien": ["Slovenien", "Ungern", "Serbien", "Bosnien och Hercegovina", "Montenegro"],
  "Slovenien": ["Italien", "Österrike", "Ungern", "Kroatien"],
  "Bosnien och Hercegovina": ["Kroatien", "Serbien", "Montenegro"],
  "Serbien": ["Ungern", "Rumänien", "Bulgarien", "Nordmakedonien", "Kosovo", "Montenegro", "Bosnien och Hercegovina", "Kroatien"],
  "Montenegro": ["Kroatien", "Bosnien och Hercegovina", "Serbien", "Kosovo", "Albanien"],
  "Nordmakedonien": ["Serbien", "Kosovo", "Albanien", "Grekland", "Bulgarien"],
  "Albanien": ["Montenegro", "Kosovo", "Nordmakedonien", "Grekland"],
  "Estland": ["Lettland", "Ryssland"],
  "Lettland": ["Estland", "Litauen", "Vitryssland", "Ryssland"],
  "Litauen": ["Lettland", "Vitryssland", "Polen"],
  "Ukraina": ["Polen", "Slovakien", "Ungern", "Rumänien", "Moldavien", "Vitryssland", "Ryssland"],
  "Moldavien": ["Rumänien", "Ukraina"],
  "Malta": [],
  "Cypern": [],

  "USA": ["Kanada", "Mexiko"],
  "Kanada": ["USA"],
  "Mexiko": ["USA", "Guatemala", "Belize"],
  "Guatemala": ["Mexiko", "Belize", "Honduras", "El Salvador"],
  "Belize": ["Mexiko", "Guatemala"],
  "Honduras": ["Guatemala", "El Salvador", "Nicaragua"],
  "Costa Rica": ["Nicaragua", "Panama"],
  "Panama": ["Costa Rica", "Colombia"],
  "Kuba": [],
  "Jamaica": [],
  "Dominikanska republiken": ["Haiti"],
  "Puerto Rico": [],
  "Colombia": ["Panama", "Venezuela", "Brasilien", "Peru", "Ecuador"],
  "Venezuela": ["Colombia", "Brasilien", "Guyana"],
  "Ecuador": ["Colombia", "Peru"],
  "Peru": ["Ecuador", "Colombia", "Brasilien", "Bolivia", "Chile"],
  "Bolivia": ["Peru", "Brasilien", "Paraguay", "Argentina", "Chile"],
  "Chile": ["Peru", "Bolivia", "Argentina"],
  "Argentina": ["Chile", "Bolivia", "Paraguay", "Brasilien", "Uruguay"],
  "Uruguay": ["Argentina", "Brasilien"],
  "Paraguay": ["Bolivia", "Brasilien", "Argentina"],
  "Brasilien": ["Uruguay", "Argentina", "Paraguay", "Bolivia", "Peru", "Colombia", "Venezuela", "Guyana", "Surinam", "Franska Guyana"],

  "Sydafrika": ["Namibia", "Botswana", "Zimbabwe", "Moçambique", "Eswatini", "Lesotho"],
  "Botswana": ["Namibia", "Sydafrika", "Zimbabwe", "Zambia"],
  "Namibia": ["Sydafrika", "Botswana", "Zambia", "Angola"],
  "Lesotho": ["Sydafrika"],
  "Eswatini": ["Sydafrika", "Moçambique"],
  "Kenya": ["Tanzania", "Uganda", "Etiopien", "Somalia"],
  "Uganda": ["Kenya", "Tanzania", "Rwanda", "Demokratiska republiken Kongo", "Sydsudan"],
  "Rwanda": ["Uganda", "Tanzania", "Demokratiska republiken Kongo", "Burundi"],
  "Tanzania": ["Kenya", "Uganda", "Rwanda", "Demokratiska republiken Kongo", "Zambia", "Malawi", "Moçambique"],
  "Senegal": ["Mauretanien", "Mali", "Guinea", "Guinea-Bissau", "Gambia"],
  "Ghana": ["Elfenbenskusten", "Burkina Faso", "Togo"],
  "Nigeria": ["Benin", "Niger", "Tchad", "Kamerun"],
  "Egypten": ["Libyen", "Sudan", "Israel"],
  "Tunisien": ["Algeriet", "Libyen"],
  "Marocko": ["Algeriet"],
  "Madagaskar": [],
  "Mauritius": [],
  "Réunion": [],

  "Turkiet": ["Grekland", "Bulgarien", "Georgien", "Armenien", "Iran", "Irak", "Syrien"],
  "Israel": ["Egypten", "Jordanien", "Libanon", "Syrien"],
  "Jordanien": ["Israel", "Syrien", "Irak", "Saudiarabien"],
  "Förenade Arabemiraten": ["Saudiarabien", "Oman"],
  "Saudiarabien": ["Jordanien", "Irak", "Kuwait", "Qatar", "Förenade Arabemiraten", "Oman", "Jemen"],
  "Qatar": ["Saudiarabien"],
  "Kuwait": ["Irak", "Saudiarabien"],
  "Oman": ["Förenade Arabemiraten", "Saudiarabien", "Jemen"],
  "Indien": ["Pakistan", "Kina", "Nepal", "Bhutan", "Bangladesh", "Myanmar"],
  "Sri Lanka": [],
  "Nepal": ["Indien", "Kina"],
  "Bangladesh": ["Indien", "Myanmar"],
  "Thailand": ["Myanmar", "Laos", "Kambodja", "Malaysia"],
  "Malaysia": ["Thailand", "Singapore", "Indonesien"],
  "Singapore": ["Malaysia"],
  "Indonesien": ["Malaysia", "Papua Nya Guinea", "Östtimor"],
  "Filippinerna": [],
  "Vietnam": ["Kina", "Laos", "Kambodja"],
  "Kambodja": ["Thailand", "Vietnam", "Laos"],
  "Laos": ["Kina", "Vietnam", "Kambodja", "Thailand", "Myanmar"],
  "Kina": ["Ryssland", "Mongoliet", "Kazakstan", "Kirgizistan", "Tadzjikistan", "Afghanistan", "Pakistan", "Indien", "Nepal", "Bhutan", "Vietnam", "Laos", "Nordkorea"],
  "Japan": [],
  "Sydkorea": ["Nordkorea"],
  "Taiwan": [],
  "Mongoliet": ["Ryssland", "Kina"],
  "Kazakstan": ["Ryssland", "Kina", "Kirgizistan", "Uzbekistan", "Turkmenistan"],
  "Georgien": ["Ryssland", "Turkiet", "Armenien", "Azerbajdzjan"],
  "Armenien": ["Georgien", "Azerbajdzjan", "Turkiet", "Iran"],
  "Azerbajdzjan": ["Ryssland", "Georgien", "Armenien", "Iran"],

  "Australien": [],
  "Nya Zeeland": []
};

// Extra länder (utan frö-koordinat, används aldrig som slumpad startpunkt)
// enbart för att kunna avgöra kontinent om en panorama-sökning skulle
// landa i ett grannland som inte finns i listan ovan.
window.STREETVIEW_CONTINENT_FALLBACK = {
  "Vatikanstaten": "Europa",
  "San Marino": "Europa",
  "Monaco": "Europa",
  "Andorra": "Europa",
  "Liechtenstein": "Europa",
  "Kosovo": "Europa",
  "Vitryssland": "Europa",
  "Ryssland": "Europa",
  "Iran": "Asien",
  "Irak": "Asien",
  "Syrien": "Asien",
  "Libanon": "Asien",
  "Jemen": "Asien",
  "Bahrain": "Asien",
  "Afghanistan": "Asien",
  "Pakistan": "Asien",
  "Bhutan": "Asien",
  "Brunei": "Asien",
  "Östtimor": "Asien",
  "Nordkorea": "Asien",
  "Turkmenistan": "Asien",
  "Uzbekistan": "Asien",
  "Kirgizistan": "Asien",
  "Tadzjikistan": "Asien",
  "Papua Nya Guinea": "Oceanien",
  "Fiji": "Oceanien",
  "Salomonöarna": "Oceanien",
  "Vanuatu": "Oceanien",
  "Samoa": "Oceanien",
  "Tonga": "Oceanien",
  "Haiti": "Nordamerika",
  "Bahamas": "Nordamerika",
  "Trinidad och Tobago": "Nordamerika",
  "Barbados": "Nordamerika",
  "Grenada": "Nordamerika",
  "Saint Lucia": "Nordamerika",
  "Dominica": "Nordamerika",
  "Surinam": "Sydamerika",
  "Guyana": "Sydamerika",
  "Franska Guyana": "Sydamerika",
  "Zimbabwe": "Afrika",
  "Zambia": "Afrika",
  "Malawi": "Afrika",
  "Moçambique": "Afrika",
  "Angola": "Afrika",
  "Demokratiska republiken Kongo": "Afrika",
  "Kongo-Brazzaville": "Afrika",
  "Gabon": "Afrika",
  "Ekvatorialguinea": "Afrika",
  "Centralafrikanska republiken": "Afrika",
  "Tchad": "Afrika",
  "Sudan": "Afrika",
  "Sydsudan": "Afrika",
  "Etiopien": "Afrika",
  "Eritrea": "Afrika",
  "Djibouti": "Afrika",
  "Somalia": "Afrika",
  "Komorerna": "Afrika",
  "Seychellerna": "Afrika",
  "Kap Verde": "Afrika",
  "Guinea-Bissau": "Afrika",
  "Guinea": "Afrika",
  "Sierra Leone": "Afrika",
  "Liberia": "Afrika",
  "Elfenbenskusten": "Afrika",
  "Togo": "Afrika",
  "Benin": "Afrika",
  "Burkina Faso": "Afrika",
  "Mali": "Afrika",
  "Niger": "Afrika",
  "Mauretanien": "Afrika",
  "Libyen": "Afrika",
  "Algeriet": "Afrika"
};
